services:
    db:
        image: mcr.microsoft.com/mssql/server
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: Project@123
        ports:
            - 1433:1433
        volumes:
            - sqlvolume:/var/opt/mssql
volumes:
    sock:
    sqlvolume:
